apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: your-registry/gateway-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          value: "production"
        - name: SERVICE_PORT
          value: "3003"
        - name: USER_SERVICE_URL
          value: "http://user-service:3000"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:3001"
        - name: ORDER_SERVICE_URL
          value: "http://order-service:3002"
        # If this is an express-based gateway that proxies, set proxy-related envs:
        - name: PROXY_TIMEOUT
          value: "30000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "150m"
          limits:
            memory: "300Mi"
            cpu: "700m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
